<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 * @package Sherlock\components\queries
 */
namespace Sherlock\components\queries;

use Sherlock\components;

/**
 * @method \Sherlock\components\queries\Boosting positive() positive(\sherlock\components\QueryInterface $value)
 * @method \Sherlock\components\queries\Boosting negative() negative(\sherlock\components\QueryInterface $value)
 * @method \Sherlock\components\queries\Boosting negative_boost() negative_boost(\float $value) Default: 0.2

 */
class Boosting extends \Sherlock\components\BaseComponent implements \Sherlock\components\QueryInterface
{
    public function __construct($hashMap = null)
    {
        $this->params['negative_boost'] = 0.2;

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = array (
  'boosting' =>
  array (
    'positive' => $this->params["positive"]->toArray(),
    'negative' => $this->params["negative"]->toArray(),
    'negative_boost' => $this->params["negative_boost"],
  )
);

        return $ret;
    }

}
