<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\ConstantScore filter() filter(\sherlock\components\FilterInterface $value)
 * @method \sherlock\components\queries\ConstantScore boost() boost(float $value) Default: 1.2

 */
class ConstantScore extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct($hashMap = null)
	{
		$this->params['boost'] = 1.2;

		parent::__construct($hashMap);
	}
	
	public function toArray()
	{
		$ret = array (
  'constant_score' => 
  array (
    'filter' => $this->params["filter"]->toArray(),
    'boost' => $this->params["boost"],
  ),
);
		return $ret;
	}

}

?>