<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-09
 * Time: 07:18 PM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\ConstantScore filter() filter(\sherlock\components\FilterInterface $value)
 * @method \sherlock\components\queries\ConstantScore boost() boost(float $value) Default: 1.2

 */
class ConstantScore extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct()
	{
		$this->params['$boost'] = 1.2;

	}
}

?>