<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 * @package Sherlock\components\queries
 */
namespace Sherlock\components\queries;

use Sherlock\components;

/**
 * @method \Sherlock\components\queries\CustomScore query() query(\sherlock\components\QueryInterface $value)
 * @method \Sherlock\components\queries\CustomScore params() params(array $value)
 * @method \Sherlock\components\queries\CustomScore script() script(\string $value)
 * @method \Sherlock\components\queries\CustomScore lang() lang(\string $value) Default: "mvel"

 */
class CustomScore extends \Sherlock\components\BaseComponent implements \Sherlock\components\QueryInterface
{
    public function __construct($hashMap = null)
    {
        $this->params['lang'] = "mvel";

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = array (
  'custom_score' =>
  array (
    'query' => $this->params["query"]->toArray(),
    'params' => $this->params["params"],
    'script' => $this->params["script"],
    'lang' => $this->params["lang"],
  ),
);

        return $ret;
    }

}
