<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 * @package Sherlock\components\queries
 */
namespace Sherlock\components\queries;

use Sherlock\components;
use Sherlock\components\QueryInterface;

/**
 * Class CustomScore
 * @package Sherlock\components\queries
 */
class CustomScore extends components\BaseComponent implements QueryInterface
{
    /**
     * @param QueryInterface $value
     *
     * @return $this
     */
    public function query(QueryInterface $value)
    {
        $this->params['query'] = $value->toArray();
        return $this;
    }


    /**
     * @param string $value
     *
     * @return $this
     */
    public function params($value)
    {
        $this->params['params'] = $value;
        return $this;
    }


    /**
     * @param string $value
     *
     * @return $this
     */
    public function script($value)
    {
        $this->params['script'] = $value;
        return $this;
    }


    /**
     * @param string $value
     *
     * @return $this
     */
    public function lang($value)
    {
        $this->params['lang'] = $value;
        return $this;
    }


    /**
     * @return array
     */
    public function toArray()
    {
        $params = $this->convertParams(
            array(
                'query',
                'params',
                'script',
                'lang',
            )
        );

        $ret = array('custom_score' => $params);

        return $ret;
    }

}
