<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 * @package Sherlock\components\queries
 */
namespace Sherlock\components\queries;

use Sherlock\components;
use Sherlock\components\QueryInterface;

/**
 * Class CustomBoostFactor
 * @package Sherlock\components\queries
 */
class CustomBoostFactor extends components\BaseComponent implements QueryInterface
{

    /**
     * @param QueryInterface $value
     *
     * @return $this
     */
    public function query(QueryInterface $value)
    {
        $this->params['query'] = $value->toArray();
        return $this;
    }


    /**
     * @param $value
     *
     * @return $this
     */
    public function boost_factor($value)
    {
        $this->params['boost_factor'] = $value;
        return $this;
    }


    /**
     * @return array
     */
    public function toArray()
    {
        $params = $this->convertParams(
            array(
                'query',
                'boost_factor',
            )
        );

        $ret = array('custom_boost_factor' => $params);

        return $ret;
    }

}
