<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-13
 * Time: 08:40 AM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\FilteredQuery query() query(\sherlock\components\QueryInterface $value)
 * @method \sherlock\components\queries\FilteredQuery filter() filter(\sherlock\components\FilterInterface $value)

 */
class FilteredQuery extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct($hashMap = null)
	{

		parent::__construct($hashMap);
	}
}

?>