<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 * @package Sherlock\components\queries
 */
namespace Sherlock\components\queries;

use Sherlock\components;

/**
 * @method \Sherlock\components\queries\FilteredQuery query() query(\sherlock\components\QueryInterface $value)
 * @method \Sherlock\components\queries\FilteredQuery filter() filter(\sherlock\components\FilterInterface $value)

 */
class FilteredQuery extends \Sherlock\components\BaseComponent implements \Sherlock\components\QueryInterface
{
    public function __construct($hashMap = null)
    {

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = array (
  'filtered' =>
  array (
    'query' => $this->params["query"]->toArray(),
    'filter' => $this->params["filter"],
  ),
);

        return $ret;
    }

}
