<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 * @package Sherlock\components\queries
 */
namespace Sherlock\components\queries;

use Sherlock\components;
use Sherlock\components\QueryInterface;

/**
 * Class FuzzyLikeThis
 * @package Sherlock\components\queries
 */
class FuzzyLikeThis extends components\BaseComponent implements QueryInterface
{
    /**
     * @param array $value
     *
     * @return $this
     */
    public function fields($value)
    {
        $this->params['fields'] = $value;
        return $this;
    }

    /**
     * @param string $value
     *
     * @return $this
     */
    public function like_text($value)
    {
        $this->params['like_text'] = $value;
        return $this;
    }

    /**
     * @param int $value
     *
     * @return $this
     */
    public function max_query_terms($value)
    {
        $this->params['max_query_terms'] = $value;
        return $this;
    }

    /**
     * @param string $value
     *
     * @return $this
     */
    public function analyzer($value)
    {
        $this->params['analyzer'] = $value;
        return $this;
    }

    /**
     * @param bool $value
     *
     * @return $this
     */
    public function ignore_tf($value)
    {
        $this->params['ignore_tf'] = $value;
        return $this;
    }

    /**
     * @param float $value
     *
     * @return $this
     */
    public function boost($value)
    {
        $this->params['boost'] = $value;
        return $this;
    }

    /**
     * @param float $value
     *
     * @return $this
     */
    public function min_similarity($value)
    {
        $this->params['min_similarity'] = $value;
        return $this;
    }

    /**
     * @param int $value
     *
     * @return $this
     */
    public function prefix_length($value)
    {
        $this->params['prefix_length'] = $value;
        return $this;
    }


    /**
     * @return array
     */
    public function toArray()
    {
        $params = $this->convertParams(
            array(
                'fields',
                'like_text',
                'max_query_terms',
                'min_similarity',
                'prefix_length',
                'boost',
                'analyzer',
                'ignore_tf',
            )
        );

        $ret = array('fuzzy_like_this' => $params);

        return $ret;
    }

}
