<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-09
 * Time: 07:18 PM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\FuzzyLikeThis fields() fields(array $value)
 * @method \sherlock\components\queries\FuzzyLikeThis like_text() like_text(string $value)
 * @method \sherlock\components\queries\FuzzyLikeThis max_query_terms() max_query_terms(int $value) Default: 10
 * @method \sherlock\components\queries\FuzzyLikeThis min_similarity() min_similarity(float $value) Default: 0.5
 * @method \sherlock\components\queries\FuzzyLikeThis prefix_length() prefix_length(int $value) Default: 3
 * @method \sherlock\components\queries\FuzzyLikeThis boost() boost(float $value) Default: 2.0
 * @method \sherlock\components\queries\FuzzyLikeThis analyzer() analyzer(string $value) Default: "default"
 * @method \sherlock\components\queries\FuzzyLikeThis ignore_tf() ignore_tf(string $value) Default: "false"

 */
class FuzzyLikeThis extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct()
	{
		$this->params['$max_query_terms'] = 10;
$this->params['$min_similarity'] = 0.5;
$this->params['$prefix_length'] = 3;
$this->params['$boost'] = 2.0;
$this->params['$analyzer'] = "default";
$this->params['$ignore_tf'] = "false";

	}
}

?>