<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:10 PM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\HasChild type() type(string $value)
 * @method \sherlock\components\queries\HasChild score_type() score_type(string $value) Default: "sum"
 * @method \sherlock\components\queries\HasChild query() query(QueryIntefrace $value)

 */
class HasChild extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct($hashMap = null)
	{
		$this->params['score_type'] = "sum";

		parent::__construct($hashMap);
	}
	
	public function toArray()
	{
		$ret = array (
  'has_child' => 
  array (
    'type' => $this->params["type"],
    'score_type' => $this->params["score_type"],
    'query' => $this->params["query"],
  ),
);
		return $ret;
	}
	
	public function toJSON()
	{
		return parent::toJSON();
	}
}

?>