<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 * @package Sherlock\components\queries
 */
namespace Sherlock\components\queries;

use Sherlock\components;
use Sherlock\components\QueryInterface;

class HasChild extends components\BaseComponent implements QueryInterface
{
    /**
     * @param string $value
     *
     * @return $this
     */
    public function type($value)
    {
        $this->params['type'] = $value;
        return $this;
    }

    /**
     * @param string $value
     *
     * @return $this
     */
    public function score_type($value)
    {
        $this->params['score_type'] = $value;
        return $this;
    }


    /**
     * @param QueryInterface $value
     *
     * @return $this
     */
    public function query(QueryInterface $value)
    {
        $this->params['query'] = $value->toArray();
        return $this;
    }


    /**
     * @return array
     */
    public function toArray()
    {
        $params = $this->convertParams(
            array(
                'type',
                'score_type',
                'query',
            )
        );

        $ret = array('has_child' => $params);

        return $ret;
    }

}
