<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 * @package Sherlock\components\queries
 */
namespace Sherlock\components\queries;

use Sherlock\components;

/**
 * @method \Sherlock\components\queries\HasChild type() type(\string $value)
 * @method \Sherlock\components\queries\HasChild score_type() score_type(\string $value) Default: "sum"
 * @method \Sherlock\components\queries\HasChild query() query(\sherlock\components\QueryInterface $value)

 */
class HasChild extends \Sherlock\components\BaseComponent implements \Sherlock\components\QueryInterface
{
    public function __construct($hashMap = null)
    {
        $this->params['score_type'] = "sum";

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = array (
  'has_child' =>
  array (
    'type' => $this->params["type"],
    'score_type' => $this->params["score_type"],
    'query' => $this->params["query"]->toArray(),
  ),
);

        return $ret;
    }

}
