<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 * @package Sherlock\components\queries
 */
namespace Sherlock\components\queries;

use Sherlock\components;

/**
 * @method \Sherlock\components\queries\Ids type() type(\string $value)
 * @method \Sherlock\components\queries\Ids values() values(array $value)

 */
class Ids extends \Sherlock\components\BaseComponent implements \Sherlock\components\QueryInterface
{
    public function __construct($hashMap = null)
    {

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = array (
  'ids' =>
  array (
    'type' => $this->params["type"],
    'values' => $this->params["values"],
  ),
);

        return $ret;
    }

}
