<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:10 PM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\Ids type() type(string $value)
 * @method \sherlock\components\queries\Ids values() values(array $value)

 */
class Ids extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct($hashMap = null)
	{

		parent::__construct($hashMap);
	}
	
	public function toArray()
	{
		$ret = array (
  'ids' => 
  array (
    'type' => $this->params["type"],
    'values' => $this->params["values"],
  ),
);
		return $ret;
	}
	
	public function toJSON()
	{
		return parent::toJSON();
	}
}

?>