<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 */
namespace Sherlock\components\queries;

use Sherlock\components;

/**
 * @method \Sherlock\components\queries\Indices no_match_query() no_match_query(\sherlock\components\QueryInterface $value)
 * @method \Sherlock\components\queries\Indices query() query(\sherlock\components\QueryInterface $value)
 */
class Indices extends \Sherlock\components\BaseComponent implements \Sherlock\components\QueryInterface
{
    public function __construct($hashMap = null)
    {

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = array (
  'indices' =>
  array (
    'indices' => $this->params["indices"],
    'query' => $this->params["query"],
    'no_match_query' => $this->params["no_match_query"],
  ),
);

        return $ret;
    }

}
