<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:10 PM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\MatchAll boost() boost(float $value) Default: 1

 */
class MatchAll extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct($hashMap = null)
	{
		$this->params['boost'] = 1;

		parent::__construct($hashMap);
	}
	
	public function toArray()
	{
		$ret = array (
  'match_all' => 
  array (
    'boost' => $this->params["boost"],
  ),
);
		return $ret;
	}
	
	public function toJSON()
	{
		return parent::toJSON();
	}
}

?>