<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-13
 * Time: 08:40 AM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\MoreLikeThisField field() field(array $value)
 * @method \sherlock\components\queries\MoreLikeThisField like_text() like_text(string $value)
 * @method \sherlock\components\queries\MoreLikeThisField min_term_freq() min_term_freq(int $value) Default: 2
 * @method \sherlock\components\queries\MoreLikeThisField max_query_terms() max_query_terms(int $value) Default: 25
 * @method \sherlock\components\queries\MoreLikeThisField percent_terms_to_match() percent_terms_to_match(float $value) Default: 0.3
 * @method \sherlock\components\queries\MoreLikeThisField stop_words() stop_words(array $value) Default: array()
 * @method \sherlock\components\queries\MoreLikeThisField min_doc_freq() min_doc_freq(int $value) Default: 5
 * @method \sherlock\components\queries\MoreLikeThisField max_doc_freq() max_doc_freq(int $value) Default: 0
 * @method \sherlock\components\queries\MoreLikeThisField min_word_len() min_word_len(int $value) Default: 0
 * @method \sherlock\components\queries\MoreLikeThisField max_word_len() max_word_len(int $value) Default: 0
 * @method \sherlock\components\queries\MoreLikeThisField boost_terms() boost_terms(int $value) Default: 1
 * @method \sherlock\components\queries\MoreLikeThisField boost() boost(float $value) Default: 1.0

 */
class MoreLikeThisField extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct($hashMap = null)
	{
		$this->params['min_term_freq'] = 2;
		$this->params['max_query_terms'] = 25;
		$this->params['percent_terms_to_match'] = 0.3;
		$this->params['stop_words'] = array();
		$this->params['min_doc_freq'] = 5;
		$this->params['max_doc_freq'] = 0;
		$this->params['min_word_len'] = 0;
		$this->params['max_word_len'] = 0;
		$this->params['boost_terms'] = 1;
		$this->params['boost'] = 1.0;

		parent::__construct($hashMap);
	}
}

?>