<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-13
 * Time: 08:40 AM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\Nested path() path(string $value)
 * @method \sherlock\components\queries\Nested score_mode() score_mode(string $value) Default: "avg"
 * @method \sherlock\components\queries\Nested query() query(\sherlock\components\QueryInterface $value)

 */
class Nested extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct($hashMap = null)
	{
		$this->params['score_mode'] = "avg";

		parent::__construct($hashMap);
	}
}

?>