<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-09
 * Time: 07:18 PM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\Nested path() path(string $value)
 * @method \sherlock\components\queries\Nested score_mode() score_mode(string $value) Default: "avg"
 * @method \sherlock\components\queries\Nested query() query(\sherlock\components\QueryInterface $value)

 */
class Nested extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct()
	{
		$this->params['$score_mode'] = "avg";

	}
}

?>