<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-09
 * Time: 07:18 PM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\Prefix field() field(string $value)
 * @method \sherlock\components\queries\Prefix value() value(string $value)
 * @method \sherlock\components\queries\Prefix boost() boost(float $value) Default: 2.0
 * @method \sherlock\components\queries\Prefix analyzer() analyzer(string $value) Default: "default"
 * @method \sherlock\components\queries\Prefix slop() slop(int $value) Default: 3
 * @method \sherlock\components\queries\Prefix max_expansions() max_expansions(int $value) Default: 100

 */
class Prefix extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct()
	{
		$this->params['$boost'] = 2.0;
$this->params['$analyzer'] = "default";
$this->params['$slop'] = 3;
$this->params['$max_expansions'] = 100;

	}
}

?>