<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-09
 * Time: 07:18 PM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\QueryStringMultiField query() query(string $value)
 * @method \sherlock\components\queries\QueryStringMultiField fields() fields(array $value)
 * @method \sherlock\components\queries\QueryStringMultiField boost() boost(float $value) Default: 2.0
 * @method \sherlock\components\queries\QueryStringMultiField enable_position_increments() enable_position_increments(int $value) Default: 1
 * @method \sherlock\components\queries\QueryStringMultiField default_operator() default_operator(string $value) Default: "OR"
 * @method \sherlock\components\queries\QueryStringMultiField analyzer() analyzer(string $value) Default: "default"
 * @method \sherlock\components\queries\QueryStringMultiField allow_leading_wildcard() allow_leading_wildcard(int $value) Default: 0
 * @method \sherlock\components\queries\QueryStringMultiField lowercase_expanded_terms() lowercase_expanded_terms(int $value) Default: 1
 * @method \sherlock\components\queries\QueryStringMultiField fuzzy_min_sim() fuzzy_min_sim(float $value) Default: 0.5
 * @method \sherlock\components\queries\QueryStringMultiField fuzzy_prefix_length() fuzzy_prefix_length(int $value) Default: 2
 * @method \sherlock\components\queries\QueryStringMultiField lenient() lenient(int $value) Default: 1
 * @method \sherlock\components\queries\QueryStringMultiField phrase_slop() phrase_slop(int $value) Default: 10
 * @method \sherlock\components\queries\QueryStringMultiField analyze_wildcard() analyze_wildcard(int $value) Default: 1
 * @method \sherlock\components\queries\QueryStringMultiField auto_generate_phrase_queries() auto_generate_phrase_queries(int $value) Default: 0
 * @method \sherlock\components\queries\QueryStringMultiField rewrite() rewrite(string $value) Default: "constant_score_default"
 * @method \sherlock\components\queries\QueryStringMultiField quote_analyzer() quote_analyzer(string $value) Default: "standard"
 * @method \sherlock\components\queries\QueryStringMultiField quote_field_suffix() quote_field_suffix(string $value) Default: ".unstemmed"
 * @method \sherlock\components\queries\QueryStringMultiField use_dis_max() use_dis_max(string $value) Default: "true"
 * @method \sherlock\components\queries\QueryStringMultiField tie_breaker() tie_breaker(int $value) Default: 1

 */
class QueryStringMultiField extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct()
	{
		$this->params['$boost'] = 2.0;
$this->params['$enable_position_increments'] = 1;
$this->params['$default_operator'] = "OR";
$this->params['$analyzer'] = "default";
$this->params['$allow_leading_wildcard'] = 0;
$this->params['$lowercase_expanded_terms'] = 1;
$this->params['$fuzzy_min_sim'] = 0.5;
$this->params['$fuzzy_prefix_length'] = 2;
$this->params['$lenient'] = 1;
$this->params['$phrase_slop'] = 10;
$this->params['$analyze_wildcard'] = 1;
$this->params['$auto_generate_phrase_queries'] = 0;
$this->params['$rewrite'] = "constant_score_default";
$this->params['$quote_analyzer'] = "standard";
$this->params['$quote_field_suffix'] = ".unstemmed";
$this->params['$use_dis_max'] = "true";
$this->params['$tie_breaker'] = 1;

	}
}

?>