<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-13
 * Time: 07:18 AM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\Raw Raw() Raw(string $json)

 */
class Raw extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct($hashMap)
	{
		if (!isset($hashMap))
		{
			throw new \sherlock\common\exceptions\BadMethodCallException("Hashmap must be provided for the Raw query");
		}


		if (is_array(($hashMap)) && count($hashMap) > 0)
		{
			//Raw array hash map provided
			//put it right into the params
			$this->params['hash'] = $hashMap;
		}
		elseif (is_string($hashMap))
		{
			//Raw JSON has been provided
			//Decode from JSON into array
			$this->params['hash'] = json_decode($hashMap, true);
		}

	}

	public function toArray()
	{
		return $this->params['hash'];
	}
}

?>