<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 */
namespace Sherlock\components\queries;

use Sherlock\components;

/**
 * @method \Sherlock\components\queries\Terms field() field(string $value)
 * @method \Sherlock\components\queries\Terms term() term(array $value)
 * @method \Sherlock\components\queries\Terms minimum_match() minimum_match(int $value) Default: 2

 */
class Terms extends \Sherlock\components\BaseComponent implements \Sherlock\components\QueryInterface
{
    public function __construct($hashMap = null)
    {
        $this->params['minimum_match'] = 2;

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = array (
  'terms' =>
  array (
    $this->params["field"] =>
    array (
      'value' => $this->params["term"],
      'minimum_match' => $this->params["minimum_match"],
    ),
  ),
);

        return $ret;
    }

}
