<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-09
 * Time: 07:18 PM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\TopChildren type() type(string $value)
 * @method \sherlock\components\queries\TopChildren query() query(\sherlock\components\QueryInterface $value)
 * @method \sherlock\components\queries\TopChildren score() score(string $value) Default: "max"
 * @method \sherlock\components\queries\TopChildren factor() factor(int $value) Default: 5
 * @method \sherlock\components\queries\TopChildren incremental_factor() incremental_factor(int $value) Default: 5

 */
class TopChildren extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct()
	{
		$this->params['$score'] = "max";
$this->params['$factor'] = 5;
$this->params['$incremental_factor'] = 5;

	}
}

?>