<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-16
 * Time: 09:24 PM
 * Auto-generated by "generate.php"
 */
namespace sherlock\components\queries;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\queries\Wildcard field() field(string $value)
 * @method \sherlock\components\queries\Wildcard value() value(string $value)
 * @method \sherlock\components\queries\Wildcard boost() boost(float $value) Default: 1.0

 */
class Wildcard extends \sherlock\components\BaseComponent implements \sherlock\components\QueryInterface
{
	public function __construct($hashMap = null)
	{
		$this->params['boost'] = 1.0;

		parent::__construct($hashMap);
	}
	
	public function toArray()
	{
		$ret = array (
  'wildcard' => 
  array (
    $this->params["field"] => 
    array (
      'value' => $this->params["value"],
      'boost' => $this->params["boost"],
    ),
  ),
);
		return $ret;
	}

}

?>