<?php
namespace sherlock;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-07 at 03:12:53.
 */
class SherlockTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Sherlock
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Sherlock;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers sherlock\Sherlock::query
     */
    public function testBuildQuery()
    {
		$req = sherlock::search();
		$req->indices('test', 'test2');
		$req->query = sherlock::query()->Term();


		$req->query()->Term()->field("testField")->term("testTerm");
		$req->execute();



    }



}
