<?php
namespace sherlock\tests\components\queries\Bool2;

use sherlock\components\queries\Bool;
use sherlock\components\queries\Term;
use sherlock\components\BaseComponent;
use sherlock\components\QueryInterface;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-07 at 03:12:53.
 */
class Term2Test extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Bool
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Bool;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}



	/**
	 * @covers sherlock\components\queries\Term2::build
	 */
	public function testToString()
	{

		$term = new \sherlock\components\queries\Term();
		$term->field("f1")->term("f2");


		$ret = $this->object->must(array($term, $term))->should($term)->must_not($term);
		echo $ret;

	}




}


?>