<?php
/**
 * User: Zachary Tong
 * Date: 2/7/13
 * Time: 5:19 AM
 */

namespace sherlock\tests\components\queries\Terms;

use sherlock\components\queries\Terms;
use sherlock\common\exceptions;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-07 at 03:12:53.
 */
class TermsTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Terms
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Terms;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers sherlock\components\queries\Term::term
	 * @covers sherlock\components\queries\Term::field
	 * @covers sherlock\components\queries\Term::boost
	 * @covers sherlock\components\queries\Term::minimum_match
	 */
	public function testValues()
	{
		$ret = $this->object->terms(array("term","term2"));
		$this->assertInstanceOf('sherlock\components\queries\Terms', $ret);

		$ret = $ret->field("field");
		$this->assertInstanceOf('sherlock\components\queries\Terms', $ret);

		$ret = $ret->boost("boost");
		$this->assertInstanceOf('sherlock\components\queries\Terms', $ret);

		$ret = $ret->minimum_match(1);
		$this->assertInstanceOf('sherlock\components\queries\Terms', $ret);

		//Chaining now
		$ret = $this->object->terms(array("term","term2"))->field("field")->boost("boost")->minimum_match(1);
		$this->assertInstanceOf('sherlock\components\queries\Terms', $ret);

	}

	/**
	 * @covers sherlock\components\queries\Terms::build
	 */
	public function testBuild()
	{
		$ret = $this->object->terms(array("term","term2"))->field("field");
		$this->assertInstanceOf('sherlock\components\queries\Terms', $ret);

		$final = $ret->build();
		$expectedFinal = array("terms" =>
							array("field" =>
								array("value" => array("term","term2"),
									"boost" => 1,
									"minimum_match" => 1
								)
							)
						);
		$this->assertEquals($expectedFinal,$final);
	}

	/**
	 * @covers sherlock\components\queries\Term::build
	 */
	public function testBuildExceptions()
	{
		//omit term
		$ret = $this->object->field("field")->boost("boost")->minimum_match(1);
		$this->assertInstanceOf('sherlock\components\queries\Terms', $ret);

		$this->setExpectedException('sherlock\common\exceptions\RuntimeException');
		$final = $ret->build();

		//omit field
		$ret = $this->object->field("term")->boost("boost")->minimum_match(1);
		$this->assertInstanceOf('sherlock\components\queries\Terms', $ret);

		$this->setExpectedException('sherlock\common\exceptions\RuntimeException');
		$final = $ret->build();

	}



}


?>