<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 */
namespace sherlock\components\filters;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\filters\Bool must() must(array $value)
 * @method \sherlock\components\filters\Bool must_not() must_not(array $value)
 * @method \sherlock\components\filters\Bool should() should(array $value)
 * @method \sherlock\components\filters\Bool _cache() _cache(bool $value) Default: false

 */
class Bool extends \sherlock\components\BaseComponent implements \sherlock\components\FilterInterface
{
	public function __construct($hashMap = null)
	{
		$this->params['_cache'] = false;

		parent::__construct($hashMap);
	}
	
	public function toArray()
	{
		$ret = array (
  'bool' => 
  array (
    'must' => $this->params["must"],
    'must_not' => $this->params["must_not"],
    'should' => $this->params["should"],
    '_cache' => $this->params["_cache"],
  ),
);
		return $ret;
	}

}

?>