<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 */
namespace sherlock\components\filters;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\filters\GeoDistance distance() distance(string $value)
 * @method \sherlock\components\filters\GeoDistance lat() lat(float $value)
 * @method \sherlock\components\filters\GeoDistance lon() lon(float $value)
 * @method \sherlock\components\filters\GeoDistance _cache() _cache(bool $value) Default: false

 */
class GeoDistance extends \sherlock\components\BaseComponent implements \sherlock\components\FilterInterface
{
	public function __construct($hashMap = null)
	{
		$this->params['_cache'] = false;

		parent::__construct($hashMap);
	}
	
	public function toArray()
	{
		$ret = array (
  'geo_distance' => 
  array (
    'distance' => $this->params["distance"],
    'pin.location' => 
    array (
      'lat' => $this->params["lat"],
      'lon' => $this->params["lon"],
    ),
    '_cache' => $this->params["_cache"],
  ),
);
		return $ret;
	}

}

?>