<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 */
namespace sherlock\components\filters;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\filters\GeoDistanceRange from() from(string $value)
 * @method \sherlock\components\filters\GeoDistanceRange lat() lat(float $value)
 * @method \sherlock\components\filters\GeoDistanceRange lon() lon(float $value)
 * @method \sherlock\components\filters\GeoDistanceRange _cache() _cache(bool $value) Default: false

 */
class GeoDistanceRange extends \sherlock\components\BaseComponent implements \sherlock\components\FilterInterface
{
	public function __construct($hashMap = null)
	{
		$this->params['_cache'] = false;

		parent::__construct($hashMap);
	}
	
	public function toArray()
	{
		$ret = NULL;
		return $ret;
	}

}

?>