<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 */
namespace sherlock\components\filters;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\filters\GeoPolygon points() points(array $value)
 * @method \sherlock\components\filters\GeoPolygon _cache() _cache(bool $value) Default: false

 */
class GeoPolygon extends \sherlock\components\BaseComponent implements \sherlock\components\FilterInterface
{
	public function __construct($hashMap = null)
	{
		$this->params['_cache'] = false;

		parent::__construct($hashMap);
	}
	
	public function toArray()
	{
		$ret = array (
  'geo_polygon' => 
  array (
    'person.location' => 
    array (
      'points' => $this->params["points"],
    ),
    '_cache' => $this->params["_cache"],
  ),
);
		return $ret;
	}

}

?>