<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 */
namespace Sherlock\components\filters;

use Sherlock\components;

/**
 * @method \Sherlock\components\filters\HasParent parent_type() parent_type(string $value)
 * @method \Sherlock\components\filters\HasParent query() query(\sherlock\components\QueryInterface $value)

 */
class HasParent extends \Sherlock\components\BaseComponent implements \Sherlock\components\FilterInterface
{
    public function __construct($hashMap = null)
    {

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = NULL;

        return $ret;
    }

}
