<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 */
namespace Sherlock\components\filters;

use Sherlock\components;

/**
 * @method \Sherlock\components\filters\Ids type() type(string $value)
 * @method \Sherlock\components\filters\Ids values() values(array $value)

 */
class Ids extends \Sherlock\components\BaseComponent implements \Sherlock\components\FilterInterface
{
    public function __construct($hashMap = null)
    {

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = array (
  'ids' =>
  array (
    'type' => $this->params["type"],
    'values' => $this->params["values"],
  ),
);

        return $ret;
    }

}
