<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 * @package Sherlock\components\filters
 */
namespace Sherlock\components\filters;

use Sherlock\components;

/**
 * @method \Sherlock\components\filters\Missing field() field(\string $value)
 * @method \Sherlock\components\filters\Missing existence() existence(\bool $value) Default: true
 * @method \Sherlock\components\filters\Missing null_value() null_value(\bool $value) Default: false

 */
class Missing extends \Sherlock\components\BaseComponent implements \Sherlock\components\FilterInterface
{
    public function __construct($hashMap = null)
    {
        $this->params['existence'] = true;
        $this->params['null_value'] = false;

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = array (
  'missing' =>
  array (
    'field' => $this->params["field"],
    'existence' => $this->params["existence"],
    'null_value' => $this->params["null_value"],
  ),
);

        return $ret;
    }

}
