<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 * @package Sherlock\components\filters
 */
namespace Sherlock\components\filters;

use Sherlock\components;

/**
 * @method \Sherlock\components\filters\Nested path() path(\string $value)
 * @method \Sherlock\components\filters\Nested query() query(\sherlock\components\QueryInterface $value)
 * @method \Sherlock\components\filters\Nested _cache() _cache(\bool $value) Default: false

 */
class Nested extends \Sherlock\components\BaseComponent implements \Sherlock\components\FilterInterface
{
    public function __construct($hashMap = null)
    {
        $this->params['_cache'] = false;

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = array (
  'nested' =>
  array (
    'path' => $this->params["path"],
    'query' => $this->params["query"],
    '_cache' => $this->params["_cache"],
  ),
);

        return $ret;
    }

}
