<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 * @package Sherlock\components\filters
 */
namespace Sherlock\components\filters;

use Sherlock\components;

/**
 * @method \Sherlock\components\filters\OrFilter _cache() _cache(\bool $value) Default: false

 */
class OrFilter extends \Sherlock\components\BaseComponent implements \Sherlock\components\FilterInterface
{
    public function __construct($hashMap = null)
    {
        $this->params['_cache'] = false;

        parent::__construct($hashMap);
    }

    /**
     * @param  \Sherlock\components\QueryInterface | \Sherlock\components\QueryInterface | array $values,... - one or more Queries can be specified individually, or an array of filters
     * @return OrFilter
     */
    public function queries($values)
    {

        $args = func_get_args();
        \Analog\Analog::log("OrFilter->Queries(".print_r($args, true).")", \Analog\Analog::DEBUG);

        //single param, array of queries\filters
        if (count($args) == 1 && is_array($args[0]))
            $args = $args[0];

        foreach ($args as $arg) {
            if ($arg instanceof \Sherlock\components\QueryInterface)
                $this->params['queries'][] = $arg->toArray();
            elseif ($arg instanceof \Sherlock\components\FilterInterface)
                $this->params['queries'][] = $arg->toArray();
        }

        //was this a set of filters?  Assume it was if the first arg is a filter
        if ($args[0] instanceof \Sherlock\components\FilterInterface)
            $this->params['queries'] = array("filters" => $this->params['queries']);

        return $this;
    }

    public function toArray()
    {
        $ret = array (
  'or' => $this->params["queries"],
  '_cache' => $this->params["_cache"],
);

        return $ret;
    }

}
