<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 * @package Sherlock\components\filters
 */
namespace Sherlock\components\filters;

use Sherlock\components;

/**
 * @method \Sherlock\components\filters\Query query() query(\sherlock\components\QueryInterface $value)
 * @method \Sherlock\components\filters\Query _cache() _cache(\bool $value) Default: false

 */
class Query extends \Sherlock\components\BaseComponent implements \Sherlock\components\FilterInterface
{
    public function __construct($hashMap = null)
    {
        $this->params['_cache'] = false;

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = array (
  'query' => $this->params["query"]->toArray(),
  '_cache' => $this->params["_cache"],
);

        return $ret;
    }

}
