<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 */
namespace sherlock\components\filters;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\filters\Query query() query(\sherlock\components\QueryInterface $value)
 * @method \sherlock\components\filters\Query _cache() _cache(bool $value) Default: false

 */
class Query extends \sherlock\components\BaseComponent implements \sherlock\components\FilterInterface
{
	public function __construct($hashMap = null)
	{
		$this->params['_cache'] = false;

		parent::__construct($hashMap);
	}
	
	public function toArray()
	{
		$ret = array (
  'query' => $this->params["query"],
  '_cache' => $this->params["_cache"],
);
		return $ret;
	}

}

?>