<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 * @package Sherlock\components\filters
 */
namespace Sherlock\components\filters;

use Sherlock\components;

/**
 * @method \Sherlock\components\filters\Range field() field(\string $value)
 * @method \Sherlock\components\filters\Range from() from(mixed $value)
 * @method \Sherlock\components\filters\Range to() to(mixed $value)
 * @method \Sherlock\components\filters\Range include_lower() include_lower(\bool $value) Default: true
 * @method \Sherlock\components\filters\Range include_upper() include_upper(\bool $value) Default: false
 * @method \Sherlock\components\filters\Range _cache() _cache(\bool $value) Default: true

 */
class Range extends \Sherlock\components\BaseComponent implements \Sherlock\components\FilterInterface
{
    public function __construct($hashMap = null)
    {

        $this->params['_cache']        = true;
        $this->params['lte'] = null;
        $this->params['gte'] = null;
        $this->params['lt'] = null;
        $this->params['gt'] = null;

        parent::__construct($hashMap);
    }


    public function toArray()
    {
        $boundaries = array();
        if (isset($this->params['lte']))
            $boundaries['lte'] = $this->params['lte'];
        if (isset($this->params['gte']))
            $boundaries['gte'] = $this->params['gte'];
        if (isset($this->params['lt']) && !isset($this->params['lte']) )
            $boundaries['lt'] = $this->params['lt'];
        if (isset($this->params['gt']) && !isset($this->params['gte']) )
            $boundaries['gt'] = $this->params['gt'];

        $ret = array(
            'range' =>
                array(
                    $this->params["field"] => $boundaries,
                    '_cache'               => $this->params["_cache"],
                ),
        );

        return $ret;
    }

}
