<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 */
namespace sherlock\components\filters;

use sherlock\components;
use sherlock\common\exceptions;


/**
 * @method \sherlock\components\filters\Script script() script(string $value)
 * @method \sherlock\components\filters\Script params() params(array $value) Default: array()
 * @method \sherlock\components\filters\Script _cache() _cache(bool $value) Default: false

 */
class Script extends \sherlock\components\BaseComponent implements \sherlock\components\FilterInterface
{
	public function __construct($hashMap = null)
	{
		$this->params['params'] = array();
		$this->params['_cache'] = false;

		parent::__construct($hashMap);
	}
	
	public function toArray()
	{
		$ret = array (
  'script' => 
  array (
    'script' => $this->params["script"],
    'params' => $this->params["params"],
    '_cache' => $this->params["_cache"],
  ),
);
		return $ret;
	}

}

?>