<?php
/**
 * User: Zachary Tong
 * Date: 2013-02-19
 * Time: 08:26 PM
 * Auto-generated by "generate.filters.php"
 */
namespace Sherlock\components\filters;

use Sherlock\components;

/**
 * @method \Sherlock\components\filters\Terms field() field(string $value)
 * @method \Sherlock\components\filters\Terms terms() terms(aray $value)
 * @method \Sherlock\components\filters\Terms execution() execution(string $value) Default: "plain"
 * @method \Sherlock\components\filters\Terms _cache() _cache(bool $value) Default: true

 */
class Terms extends \Sherlock\components\BaseComponent implements \Sherlock\components\FilterInterface
{
    public function __construct($hashMap = null)
    {
        $this->params['execution'] = "plain";
        $this->params['_cache'] = true;

        parent::__construct($hashMap);
    }

    public function toArray()
    {
        $ret = array (
  'terms' =>
  array (
    $this->params["field"] => $this->params["terms"],
    'execution' => $this->params["execution"],
    '_cache' => $this->params["_cache"],
  ),
);

        return $ret;
    }

}
